# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: my dyingDay
email: mydyingdayrocks@gmail.com
description:
author:
  name: Jeppe Bårris
  email: jeppe@barris.dk

# Grunt handles images and assets.
exclude: ['img', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico',
          'app/readme.md' # Do not render into html. File is included in dist
          ]

# include: ['.htaccess']
include: ['.nojekyll', 'CNAME']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true
permalink: pretty

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

# pygments: false
highlighter: false


collections:
  albums:
  videos:
  timeline:
  members:
  dates:
  social:


googlecode: UA-34020624-1

